packages <- c(
 "anomalize", "assertthat", "backports", "base64enc", "BH",
 "bigrquery", "bindr", "bindrcpp", "bitops", "blob", "bookdown", "boot",
 "brew", "brms", "broom", "callr", "caTools", "car",
 "caret", "cellranger", "cli", "clipr", "clisymbols", "cloudml",
 "coda", "colorspace", "crayon", "crosstalk", "curl", "data.table",
 "DBI", "DBItest", "dbplot", "dbplyr", "debugme", "desc", "devtools", "DiagrammeR",
 "dichromat", "digest", "downloader", "dplyr", "elastic", "emo",
 "evaluate", "extrafont", "extrafontdb", "fontBitstreamVera",
 "fontLiberation", "fontquiver", "forcats", "feather",
 "flexdashboard", "fs", "fulltext", "furrr", "futures", "gam", 
 "geojson", "geojsonio",
 "ggplot2", "gh", "git2r", "glmnet", "glue", "googlesheets",
 "gridExtra", "gtable", "h2o", "haven", "hexbin", "highr", "hms",
 "hrbrthemes", "htmltools", "htmlwidgets", "httpuv", "httr", "igraph",
 "influenceR", "ini", "irlba", "ISLR", "janitor", "jsonlite",
 "knitr", "keras", "kernlab", "labeling", "later", "lazyeval",
 "leaflet", "lme4", "lubridate", "magick", "magrittr", "maps",
 "maptools", "markdown", "memoise", "mime", "miniUI", "mgcv",
 "mlbench", "mnormt", "modelr", "munsell", "naniar", "nlme", "odbc", 
 "openssl", "openxlsx", "osmdata", "parsnip", "patchwork",
 "pdftools", "pillar", "plogr", "plotly", "plumber", "plyr",
 "png", "pool", "pointblank", "praise", "printr", "profvis", "promises",
 "psych", "purrr", "R6","randomForest", "ranger",
 "raster", "rcmdcheck", "RColorBrewer", "Rcpp", "readr", 
 "readxl", "recipes", "rematch", "remotes", "reprex", 
 "reshape2", "reticulate", "rgdal", "rgeos", "rgexf", "rlang", 
 "RMariaDB", "rmarkdown", "RMySQL", "robotstxt", "Rook", "roomba",
 "roxygen2", "rpart", "RPostgres", "rprojroot", "rsample",
 "rsconnect", "RSQLite", "rstan", "rstanarm", "rstudioapi", "Rttf2pt1",
 "rvest", "scales", "selectr", "sessioninfo", "sf", "shiny",
 "shinydashboard", "shinyjs", "shinytest", "snakecase", "slider",
 "sourcetools", "sp", "sparklyr", "stringi", "stringr", "survival",
 "sweep", "tensorflow", "testthat", "tibble", "tibbletime",
 "tidyr", "tidypredict", "tidyquant", "tidyselect", "tidytext", "tidyverse", 
 "timetk","tint", "tokenizers", "TurtleGraphics", "tufte", "udunits2", "units",
 "usethis", "utf8", "V8", "vcd", "viridis", "viridisLite", "visdat", 
 "visNetwork", "websocket", "whisker", "withr", "xgboost", "XML",
 "xml2", "xtable", "xts", "yaml", "yardstick", "zoo"
)
