# --> install R packages
nix-env -iA \
	nixpkgs.rPackages.almanac \
	nixpkgs.rPackages.blastula \
	nixpkgs.rPackages.bookdown \
	nixpkgs.rPackages.brms \
	nixpkgs.rPackages.broom \
	nixpkgs.rPackages.classInt \
	nixpkgs.rPackages.colorspace \
	nixpkgs.rPackages.colourpicker \
	nixpkgs.rPackages.crosstalk \
	nixpkgs.rPackages.data_table \
	nixpkgs.rPackages.DBI \
	nixpkgs.rPackages.devtools \
	nixpkgs.rPackages.DiagrammeR \
	nixpkgs.rPackages.DT \
	nixpkgs.rPackages.extrafont \
	nixpkgs.rPackages.extrafontdb \
	nixpkgs.rPackages.feather \
	nixpkgs.rPackages.flexdashboard \
	nixpkgs.rPackages.fs \
	nixpkgs.rPackages.geojson \
	nixpkgs.rPackages.geojsonio \
	nixpkgs.rPackages.glue \
	nixpkgs.rPackages.gridExtra \
	nixpkgs.rPackages.gt \
	nixpkgs.rPackages.gutenbergr \
	nixpkgs.rPackages.haven \
	nixpkgs.rPackages.hrbrthemes \
	nixpkgs.rPackages.htmltools \
	nixpkgs.rPackages.htmlwidgets \
	nixpkgs.rPackages.janitor \
	nixpkgs.rPackages.jsonlite \
	nixpkgs.rPackages.kableExtra \
	nixpkgs.rPackages.knitr \
	nixpkgs.rPackages.leaflet \
	nixpkgs.rPackages.leaflet_providers \
	nixpkgs.rPackages.lubridate \
	nixpkgs.rPackages.magick \
	nixpkgs.rPackages.magrittr \
	nixpkgs.rPackages.naniar \
	nixpkgs.rPackages.odbc \
	nixpkgs.rPackages.openssl \
	nixpkgs.rPackages.openxlsx \
	nixpkgs.rPackages.packrat \
	nixpkgs.rPackages.parsnip \
	nixpkgs.rPackages.patchwork \
	nixpkgs.rPackages.plotly \
	nixpkgs.rPackages.plumber \
	nixpkgs.rPackages.pointblank \
	nixpkgs.rPackages.purrr \
	nixpkgs.rPackages.ranger \
	nixpkgs.rPackages.RColorBrewer \
	nixpkgs.rPackages.Rcpp \
	nixpkgs.rPackages.readxl \
	nixpkgs.rPackages.recipes \
	nixpkgs.rPackages.remotes \
	nixpkgs.rPackages.renv \
	nixpkgs.rPackages.reprex \
	nixpkgs.rPackages.reticulate \
	nixpkgs.rPackages.rgdal \
	nixpkgs.rPackages.rgeos \
	nixpkgs.rPackages.rlang \
	nixpkgs.rPackages.rmarkdown \
	nixpkgs.rPackages.roxygen2 \
	nixpkgs.rPackages.rsample \
	nixpkgs.rPackages.rsconnect \
	nixpkgs.rPackages.rstan \
	nixpkgs.rPackages.rstanarm \
	nixpkgs.rPackages.rvest \
	nixpkgs.rPackages.sass \
	nixpkgs.rPackages.scales \
	nixpkgs.rPackages.sf \
	nixpkgs.rPackages.shiny \
	nixpkgs.rPackages.shinydashboard \
	nixpkgs.rPackages.shinyjs \
	nixpkgs.rPackages.shinythemes \
	nixpkgs.rPackages.slider \
	nixpkgs.rPackages.sparklyr \
	nixpkgs.rPackages.testthat \
	nixpkgs.rPackages.tibble \
	nixpkgs.rPackages.tibbletime \
	nixpkgs.rPackages.tictoc \
	nixpkgs.rPackages.tidycensus \
	nixpkgs.rPackages.tidyjson \
	nixpkgs.rPackages.tidymodels \
	nixpkgs.rPackages.tidyposterior \
	nixpkgs.rPackages.tidypredict \
	nixpkgs.rPackages.tidyr \
	nixpkgs.rPackages.tidyselect \
	nixpkgs.rPackages.tidytext \
	#nixpkgs.rPackages.tidyverse \
	nixpkgs.rPackages.tigris \
	nixpkgs.rPackages.timetk \
	nixpkgs.rPackages.tinytex \
	nixpkgs.rPackages.tune \
	nixpkgs.rPackages.usethis \
	nixpkgs.rPackages.V8 \
	nixpkgs.rPackages.vctrs \
	nixpkgs.rPackages.viridis \
	nixpkgs.rPackages.viridisLite \
	nixpkgs.rPackages.waffle \
	nixpkgs.rPackages.xml2 \
	nixpkgs.rPackages.yaml \
	nixpkgs.rPackages.yardstick 
